"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 15:03:30.473733
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=254), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('fsm_states',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=128), nullable=True),
    sa.Column('docs_folder_id', sa.String(length=128), nullable=True),
    sa.Column('spreadsheet_id', sa.String(length=128), nullable=True),
    sa.Column('sheet_dirty', sa.Boolean(), nullable=False),
    sa.Column('name_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=True)

    op.create_table('kv',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('language', sa.Enum('uz', 'ru', 'en', name='language', native_enum=False, length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_sessions_email'), ['email'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'tutor', 'leader', name='staffrole', native_enum=False, length=16), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('google_email', sa.String(length=254), nullable=True),
    sa.Column('granted_email', sa.String(length=254), nullable=True),
    sa.Column('granted_folder_id', sa.String(length=128), nullable=True),
    sa.Column('granted_permission_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_google_email'), ['google_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender', native_enum=False, length=16), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=128), nullable=True),
    sa.Column('folder_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('passport', 'cv', name='documentkind', native_enum=False, length=16), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=128), nullable=True),
    sa.Column('drive_url', sa.Text(), nullable=True),
    sa.Column('stale_drive_file_id', sa.String(length=128), nullable=True),
    sa.Column('upload_error', sa.Text(), nullable=True),
    sa.Column('upload_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'kind')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_next_attempt_at'), ['next_attempt_at'], unique=False)

    op.create_table('invites',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('admin', 'tutor', 'leader', name='staffrole', native_enum=False, length=16), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by_email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_next_attempt_at'))

    op.drop_table('documents')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_students_group_id'))

    op.drop_table('students')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_staff_google_email'))

    op.drop_table('staff')
    with op.batch_alter_table('web_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_sessions_email'))

    op.drop_table('web_sessions')
    op.drop_table('users')
    op.drop_table('kv')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_name'))

    op.drop_table('groups')
    op.drop_table('fsm_states')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
